name: flutter_hybrid_genui
description: Hybrid Flutter GenUI example powered by local and remote Genkit backends.
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  a2ui_core: ^0.1.0
  flutter:
    sdk: flutter
  genkit: ^0.15.1
  genkit_google_genai: ^0.2.12
  genkit_llamadart: ^1.4.0
  genui: ^0.10.1
  genui_genkit:
    path: ../..
  json_schema_builder: ^0.1.6
  llamadart: ^0.8.17
  path: ^1.8.3
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: true
